### ISSUE TITLE
Feature request: open containing folder

### ISSUE THREAD

**Issue by okuuva** [transmission-remote-gtk/transmission-remote-gtk#10]
It would be beneficial to have option to right click on torrent in the list and  "open containing folder" of a destination where files are being downloaded. Same functionality exists in regular transmission.

One could map a remote path to a local path and then "Open containing folder" command could open that mapped local path in default file browser. This kind of functionality can be found from "Transmisson Remote GUI" (yeah I know, there's a typo, but that's the name of the project) but unfortunately it doesn't work on the Linux port and the project is poorly maintained.

Maybe this kind of functionality could be implemented even with the current version using "Actions". Unfortunately it is poorly documented feature, should at least get info about available variables etc.

**Comment by ajf8** [comment]
Hi there,

Yes, you could use the actions functionality to do this.

**Comment by ajf8** [comment]
Sorry! Accidentally clicked close and comment too early.

Yes, you could use the actions feature to do this. 

It is documented here. https://github.com/transmission-remote-gtk/transmission-remote-gtk/wiki/Local-Command-usage

Please let me know if you can think of any way this documentation could be clearer or have any issues. To find the variable names available, you should refer to the transmission RPC documentation as mentioned in the doc, which lists all the fields.

IIRC there is a link to this wiki page in the configuration tab, I'll update it to point here on github instead of google code.
