### ISSUE TITLE
better distinguish buttons "verify" and "re-announce"

### ISSUE THREAD

**Issue by ilf** [transmission-remote-gtk/transmission-remote-gtk#123]
I have repeatedly mistakenly clicked "verify" when I instead wanted to click "re-announce".

Two reasons make these very easy to mix up after right-clicking on a torrent:

- Both have the same icon
![image](https://ptpimg.me/k020xu.png)
- Both are displayed together, "re-announce" immediately below "verify":
https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/dff54e8df6d2961495f94f9291c33455c6068bbb/src/trg-menu-bar.c#L48-L49

I propose to:

1. Create a new icon for one of them.
2. Re-order the list to not have them right after another.

(Alternatively, I would also like an option to disable displaying "re-announce" on right-click, leaving it only in the "Torrent" main toolbar menu.)

Thanks!

**Comment by LaserEyess** [comment]
The specific way those icons are listed has been deprecated in GTK3, so #136 will "fix" your issue but probably not in the way you were expecting.

**Comment by ilf** [comment]
Thanks, https://github.com/transmission-remote-gtk/transmission-remote-gtk/pull/136 changed the option icons.

Would it also be possible to re-order the options so that "verify" is not immediately above "re-announce"?

**Comment by LaserEyess** [comment]
I'm gonna be honest I don't see the utility in this. If your fear is misclicking "verify" where do you expect to move it so that you won't misclick it? I think changing years old menu orderings is a bad idea and will likely make more people angry or confused than it will help.

**Comment by ilf** [comment]
I'm not a UX expert and I do not know the reason for the current sorting, so I cannot make an informed suggestion for a new sequence.

I accept the argument of not easily changing long-established orderings.

What do you think of the alternative idea of "an option to disable displaying 'verify' on right-click, leaving it only in the 'Torrent' main toolbar menu"?

**Comment by LaserEyess** [comment]
I'm not a UI/UX expert either, I just think moving a menu button for your reasoning doesn't make sense. I guess I am not opposed to moving it, but where should it be put so that it is not accidentally clicked? 

I personally don't like the idea of removing it, even as a config option, it seems a little too niche, sorry.

**Comment by ilf** [comment]
> I guess I am not opposed to moving it, but where should it be put so that it is not accidentally clicked?

I thought a little about this. Maybe move "Copy Magnet Link" between "Verify" and "Re-Announce"?

**Comment by LaserEyess** [comment]
Could you open a new issue for this? Thinking about it, I'm already going to be changing the menu for adding labels in #166, and I'm going to be (eventually) radically changing how menus work for the GTK4 port, since `GtkMenu` and family are all gone. One potential thing to do is group similar operations by menu sections, which in this case I think would make sense. Verify/Move/Delete would go together, and Start/Pause/Re-Announce could go together as well, in their own section. I think this would look a little cleaner and solve your issue.

**Comment by ilf** [comment]
@LaserEyess I am happy to create a new issue, but I am unsure which title and content I should put in there. :)

You seem to have a better idea of how you want to work on the menus. Maybe you want to create a ticket for that?

Or tell me a few words for a rough title about a new ticket and I'll try to create it.

Thanks!
