### ISSUE TITLE
Installation Troubleshooting

### ISSUE THREAD

**Issue by username227** [transmission-remote-gtk/transmission-remote-gtk#127]
Hi,

I apologize if this is the wrong place to post this. I can't get this to install properly. When I run the make install command, it gives me an error - error 1 and aborts. I am not an expert and would appreciate a link or something that would explain what I need to do in more detail.

Thanks.

**Comment by ajf8** [comment]
Hi there,

No problem, please could you provide the output of make install, mainly the end? Otherwise it's difficult to guess what's going wrong here.

Try the latest 1.4.2 release which has just been published today - it may have a fix to make this work on recent distributions, I guess the appdata file fixes may resolve this.

Thanks

**Comment by sidml** [comment]
I was trying to install on ubuntu 20 from the git clone. I got the following errors:
`configure.ac:34: error: macro AX_IS_RELEASE is not defined. Is autoconf-archive installed?
configure.ac:32: TRG_CHECK_MACRO is expanded from...
configure.ac:34: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
`
`configure.ac:47: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:49: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
configure.ac:50: warning: macro 'AM_GNU_GETTEXT_REQUIRE_VERSION' not found in library
configure.ac:34: error: macro APPSTREAM_XML is not defined. Is appstream-glib installed?
configure.ac:32: TRG_CHECK_MACRO is expanded from...
configure.ac:34: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
`

Solution: I removed both the lines (APPSTREAM_XML & AX_IS_RELEASE) in configure.ac file. This mayn't be a good way but it got things going.

`./autogen.sh: 13: libtoolize: not found
`
Solution: `sudo apt install libtool`

`libtool is not listed in the requied libraries.
Can't exec "autopoint": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext`

Solution: `sudo apt-get install autopoint`
Again autopoint is not listed in the required libraries in README.

**Comment by TingPing** [comment]
`sudo apt-get install libgtk-3-dev automake autoconf autopoint gcc libgeoip-dev gettext autoconf-archive libappstream-dev appstream-util libcurl4-openssl-dev libjson-glib-dev libmrss0-dev libproxy-dev`

**Comment by LaserEyess** [comment]
@username227 @sidml please try with the current git master, the instructions might be a little more clear this time and meson is much easier to use than autotools.

**Comment by LaserEyess** [comment]
If you're still having issues with git master please feel free to open a new issue, but now that the build system is meson it should be much easier to build.
