### ISSUE TITLE
Add an option to rename files and folders

### ISSUE THREAD

**Issue by ogarcia** [transmission-remote-gtk/transmission-remote-gtk#2]
Other clients like [Transmission Remote GUI](http://transgui.sourceforge.net/) supports renaming files or folders. I think that uses the move command to do this.

Can you add support to rename files/folders?

**Comment by ajf8** [comment]
Hi,

I guess you've found the dialog when you right click on a torrent and select "move", and wanted to select any remote directory somehow. This used to be an *editable* combo box, so you could do that. As well as the dropdown selections which are remote directories defined in the local config, you could put anything.

Something definitely changed in GTK which has caused this to be no longer editable as the code for that dialog hadn't been touched in years. I'll try to look into this sometime, I don't really use the move feature so hadn't noticed.

**Comment by palosBA** [comment]
If it is built with gtk2 the combo box is editable, only gtk3 version has the flaw, I think.

**Comment by icf20** [comment]
how is this going ?

**Comment by ogarcia** [comment]
No. It's not fixed. You can move files, but you can't rename it.

**Comment by skobkin** [comment]
This issue as far as I understand is about renaming files and folder which is IN THE TORRENT DATA.

So basically it allows you to change naming of files you've downloaded and still seed them without errors or duplication.

@ogarcia, correct me if I'm wrong. If I'm correct then I'm looking for the same feature from transgui.
It's somewhat ridiculous. In transgui I can't filter torrents by name but can rename files, but in transmission-remote-gtk I can filter torrenst but can't rename files. So I'm keeping both clients installed at the same time. It's so frustrating.

**Comment by JohanAR** [comment]
I think this client needs to implement support for the rpc call [torrent-rename-path](https://github.com/transmission/transmission/blob/54a7cac25ad4f8d47a3198e4b2eeec13baeea99d/extras/rpc-spec.txt#L459)

**Comment by JohanAR** [comment]
I had a brief look at the code and I'm going to try to add this feature. There is however one small issue; the same file tree class is used for both adding new torrents and modifying properties of existing torrents. I believe torrent-rename-path is only possible once the torrent has been created on the transmission daemon, so there are two possible solutions:

1. Modify files tree view so that it knows if you're adding a new torrent or modifying existing, then it can show the "Rename..." option only once the torrent has been started. I think this is the easy option so it's what I'm going to try first.
2. Save a dictionary of any renamed files in the torrent add dialog, so that we can send torrent-rename-path after its creation. The code would need to be modified in a lot of places and there are more things that can go wrong so the overall complexity would be higher, so I'm going to ignore this for now even though I think it would be better if you could rename files in this dialog too.

**Comment by JohanAR** [comment]
Almost done implementing this, only need to figure out how to get the file list to update automatically afterwards.. It does a torrent-get but it doesn't update the open TrgFilesTreeView
