### ISSUE TITLE
License incompatibility between rss-glib and {hig,torrent-cell-renderer}.{c,h}

### ISSUE THREAD

**Issue by bbarenblat** [transmission-remote-gtk/transmission-remote-gtk#21]
rss-glib is licensed under the [LGPLv3](https://www.gnu.org/licenses/lgpl-3.0.en.html) or later. [src/hig.c](https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/8fab1a3/src/hig.c), [src/hig.h](https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/8fab1a3/src/hig.h), [src/torrent-cell-renderer.c](https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/8fab1a3/src/torrent-cell-renderer.c), and [src/torrent-cell-renderer.h](https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/8fab1a3/src/torrent-cell-renderer.h) are licensed under the [GPLv2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html) only. Since the LGPLv3 is incompatible with the GPLv2, binaries which incorporate both cannot be legally distributed.

The easiest way to rectify this is probably to update to Transmission’s current copies of src/hig.c, src/hig.h, src/torrent-cell-renderer.c, and src/torrent-cell-renderer.h, which allow distribution under the GPLv3. However, other solutions are possible and could constrain the licence of the project less.

**Comment by ajf8** [comment]
Thanks for bringing this to my attention.

Updating hig.c seems quite doable, but updating torrent-cell-renderer.c is less easy as it was quite heavily modified.

The other option is to just not distribute rss-glib, which is probably the right thing to do. I did it because rss-glib isn't really packaged by any distros. Maybe even use libmrss directly (even though rss-glib is a nice library).
