### ISSUE TITLE
Use GtkFileChooserNative

### ISSUE THREAD

**Issue by hadess** [transmission-remote-gtk/transmission-remote-gtk#35]
So that GTK+ automatically uses a portal to access files outside the sandbox when using Flatpak.

**Comment by LaserEyess** [comment]
@hadess is this still an issue?

**Comment by hadess** [comment]
Looks like the code still uses `gtk_file_chooser_dialog_new()` instead of the native variant, so yes.

`gtk_file_chooser_set_extra_widget()` will not work when using a portal (so inside a Flatpak), but it should still work outside it. This would be better than a non-working file chooser for Flatpak, and makes no difference to the non-Flatpak variant.

**Comment by LaserEyess** [comment]
Ok, I'll try to look into this, but in particular I don't know much about GTK, less about these differences you're describing. If you would be inclined to make a PR I'd be happy to review/test it. If you don't want to, I'll look into this but it's probably not a priority for me since I don't use flatpak for trg.
