### ISSUE TITLE
feature request: download a file (on my computer)

### ISSUE THREAD

**Issue by vindarel** [transmission-remote-gtk/transmission-remote-gtk#36]
Hi !
I thought a desktop client would allow me to download torrents once completed. Looks to me that's not the case. Must we use an external program for that ? Do you use the 'actions' preferences ?

I'd love a "download locally" button, or an easy way to call steadyflow for example.

Regards

**Comment by TingPing** [comment]
All this application does is connect to the transmission daemon and afaik it does not expose any method of transfering the downloaded content. You would have to have some other service such as an http server.

**Comment by vindarel** [comment]
Thanks for the answer. So, IMO it would be a great addition (at least an easy to link to an external app). I edited the title to stree it is a feature request :)

**Comment by TingPing** [comment]
I probably wouldn't hold my breath and you would be best off setting up your own solution.

**Comment by gkaklas** [comment]
Although trg's purpose is only to control the daemon, it would be pretty useful to have a feature like this. However:
- It doesn't seem like this can be done easily, as [Transmission's RPC spec](https://trac.transmissionbt.com/browser/trunk/extras/rpc-spec.txt) doesn't mention a way to download a specific file
- [Transdrone](https://github.com/erickok/transdroid) **does** have a button to download a selected file. But the only thing it does is open a link of the form `ftp://HOST/file/path`, so you'll have to run another piece of software to serve that file

So in order to more or less implement this functionality, a server will have to serve the files, and transmission-remote-gtk will have to execute a script/program to download them.

Something that could probably be done is to add an option to run these handlers from the menu, giving the selected file names as parameters. This also has the advantage that it is more generic and will allow the user to run a custom script for anything: downloading the file, opening it with an appropriate application, displaying a notification on the local computer and so on.

**Comment by vindarel** [comment]
This local commands feature is a good find ! It looks to cover the use case, I just couldn't make it work yet. Indeed, it is hard to write a shell script in this little box, and it is hard to see the error result if the terminal runs an external shell script, it closes immediately (and a `read` command that would pause it isn't always reached). 

I couldn't make the given script work (https://github.com/transmission-remote-gtk/transmission-remote-gtk/blob/master/extra/tpull.sh), looks like "transmission-remote" should be "…-gtk" but then the command opens a "new torrent" dialog, which is not what we want AFAIGuess.

> Maybe to improve UX there could be a right-click submenu so the user could select a script to run on a torrent

how so ? We can right click on a torrent and select a script already (they appear on the middle).

Maybe transmission-remote-gtk could include a couple of scripts, suited to interface with external popular applications, such as rsync and a graphical download manager (steadyflow) ? The best would be to have fields to choose some parameters (the target directory), but at this point we can edit a line manually.

thanks !

**Comment by ajf8** [comment]
It is supposed to be transmission-remote in that script. transmission-remote is the command line client to transmission-daemon, and this script uses it to grab the details of the torrent. If you want logs from the script you could wrap it in something like:

(
.. script contents ..
) 2>&1 | tee /tmp/trg-action.log 

Basically +1 to everything said before. It's a feature I wanted in the past, but without the daemon exposing anything to implement a download manager, this scripts feature seemed like the next best thing.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967

In general, this is out of scope. TRG is not a file manager and making it into one does not sound like a good idea imo. Some of this functionality is supported by local commands. Some of this would be better, as people have said, to implement in the daemon, too.
