### ISSUE TITLE
Minimize to Tray icon does not work

### ISSUE THREAD

**Issue by purpleleaf** [transmission-remote-gtk/transmission-remote-gtk#39]
The notification icon appears but trying to set the checkbox for  'Minimize to system tray' does not work: opening the option windows shows that the checkbox is still not checked and it is not possible to minimize the app to the tray icon.
Tested on lubuntu and Linux Mint.
I tested both the 1.1.3 version that are in repository and version 1.3.1 downloaded from Zesty.

**Comment by DiagonalArg** [comment]
I'm having the same issue.  Version 1.1.1 running on Ubuntu 16.04.  "Delete Local Torrent File After Adding" also does not persist, along with View >> Torrent Details and the Notifications.

**Comment by Seeder101** [comment]
I can confirm this too in Manjaro running the app from AUR the latest version 
I can checkbox the minimize to system tray but when I close or minimize the app it gets close

**Comment by ajf8** [comment]
I just tested this on debian stretch with LXDE and it worked. I'll see if I can try with ubuntu sometime. Maybe it's because I'm not compiling with libappindicator support. I tried installing the dev package on stretch but the configure script didn't pick them up, not sure why.

It has been a problem with the system tray and minimise to functionality that some desktop environments have a different idea of how it should work, or whether there is a "system tray" you can minimise apps to at all.

**Comment by LaserEyess** [comment]
See: https://github.com/transmission-remote-gtk/transmission-remote-gtk/issues/4#issuecomment-1277821967
