### ISSUE TITLE
Improve feedback "Couldn't connect to server"

### ISSUE THREAD

**Issue by krichter722** [transmission-remote-gtk/transmission-remote-gtk#48]
The feedback `Couldn't connect to server` of `transmission-remote-gtk` misses any information which can help the user to understand what's going on. The user should be able to fix any connection failure as fast as possible based on the principle "Don't make me think".

experienced with 1.1.1

**Comment by LaserEyess** [comment]
This value is simply a string returned from JSON-RPC, see [lastAnnounceResult](https://github.com/transmission/transmission/blob/main/extras/rpc-spec.txt#L352). Transmission sets this string when it cannot connect to the tracker, see [`announcer.cc`](https://github.com/transmission/transmission/blob/main/libtransmission/announcer.cc#L965). Since this project can only report what transmission says, and has absolutely no access to the tracker itself, this should be closed.
