### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by tastytea** [transmission-remote-gtk/transmission-remote-gtk#97]
transmission-remote-gtk uses about 51 MiB of memory (RES) shortly after startup. After about 7 days it uses ~333 MiB. I've seen it using several GiB.

I'm using version 1.4.1, installed by an [Gentoo ebuild](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-p2p/transmission-remote-gtk/transmission-remote-gtk-1.4.1.ebuild) with the use-flags `libnotify libproxy rss`. The use-flags translate to `--with-libnotify --with-libproxy --with-libmrss`.

**Comment by JohanAR** [comment]
Currently working on this. Found a couple of leaks so far but there are some more I want to fix before submitting the PR.

**Comment by ajf8** [comment]
Thanks Johan for the memory leak fixes! These are in master now, can anyone confirm this fixes the issue?

**Comment by tastytea** [comment]
I ran 9d3005cc590342b7b636b3774c41216df69e4d6b for about 6 hours. The memory consumption seems stable. It did go from ~67.5 MiB to ~70.7 MiB, I added a few torrents in that time. I measured with `LC_ALL=C pmap -x $(pidof transmission-remote-gtk) | awk '/total/ {print $4}'`.
I'll keep it running and report back in 7 days.

**Comment by JohanAR** [comment]
I think the valgrind suppression list that is in the git repository filters out genuine memory leaks too, for example if it is in a callback executed by GTK. Problem is if you remove the suppressions you get *a lot* of false positives, mostly from GTK and Pango, so I tried to manually go through as much code as I could, but there are parts that I didn't have time/energy to look at. Now it was a couple of weeks since I worked on this, but I have a vague memory of suspecting the add torrent dialog for not cleaning up properly, so that one might leak a few bytes every time you open it.

If anyone wants to continue this work but feel they might not be experienced enough to do it on their own, here are some suggestions :)
* For all widgets and other objects that are created using GTK's class system, make sure they have a finalize function where you free all dynamic allocated class private data.
* Create a "free" function for all structs that contain pointers (assuming they own the memory they point to). This makes for cleaner code and less maintenance, compared to manually freeing all members before deallocating an instance of this struct. Example:
```
static void trg_request_free(trg_request *req)
{
	if (req) {
		g_free(req->body);
		g_free(req->url);
		g_free(req->cookie);

		if (req->node)
			json_node_free(req->node);

		g_free(req);
	}
}
```
(this function already existed, I just added the free for req->node member and the req itself)
* Make sure that the corresponding free-function for a struct is used and not a plain g_free.
* For all GLists containing structs, use the struct's free-function together with g_list_free_full to free both the list and its contents.
* Make sure all strings (gchar*) are freed both if they are assigned a new value and when they go out of scope. Any call to a function whose name starts with "g_strdup" should probably have a g_free on the string just before it, unless you know the string is uninitialized (e.g. a local variable or inside a constructor).
* Check all dynamic memory that is allocated in one function, and freed in another. Is there a possibility that the second function is never called? In that case you need to make sure the memory is freed somewhere else. E.g. an async operation might have both a success-callback and an error-callback. If the functions belong to a class, it might be a good idea to add a free to the finalize function, even if the data "should be" freed before.
* Same with data that is freed in a branch (e.g. if-else), make sure there is no code path that might leak the object.

And some cleanup you can do while you're at it :)
* Remove NULL tests before g_free, since g_free does nothing if given a null pointer
* Replace `g_free(data); data = NULL;` with `g_clear_pointer(&data, g_free);`. The same for freeing any struct, just pass the struct's free-function as second argument to g_clear_pointer.

**Comment by TingPing** [comment]
@JohanAR Use the updated suppression file (and probably remove the one copied here): https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk.supp

If it still hides real leaks report them to gtk.

**Comment by tastytea** [comment]
I let it run for 7 days (total runtime 99 hours). The memory consumption was ~65.9 MiB in the beginning, ~91 MiB in the end and ~93.6 MiB max. It did spike after adding lots of torrents of course but there was also a ~10 MiB spike for seemingly no reason. 

The graph below is not 100% accurate because the computer was suspended in between and the data points were measured using a sleep-loop (some “hours” are shorter than 1 hour).

I seldomly opened dialogs, I guess less than 10 times in the 7 days.

![transmission-remote-gtk memory consumption over time](https://user-images.githubusercontent.com/3681516/100397305-40a17100-3049-11eb-85b4-4724800b19eb.png)

**Comment by JohanAR** [comment]
@tastytea with build from latest master? Would be interesting to know if my patch made any difference, or if I only found theoretical leaks :)

**Comment by tastytea** [comment]
@JohanAR From latest master (9d3005cc590342b7b636b3774c41216df69e4d6b), yes. The test I did 2020-04-23 (first post) showed an increase of 282 MiB in 7 days, so it is definitely much better now with ~25 MiB.

**Comment by ajf8** [comment]
It sounds like these memory leaks have been addressed by the fixes from @JohanAR . Shall we close this?

If the suppression file in the repo is not fit for purpose, we can either remove it from the repository or replace it with the one mentioned by @TingPing

**Comment by tastytea** [comment]
The fixes worked for me, the RAM consumption is now at around 90 MiB after 24 days.
